package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/UNKNOWN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/zulu-platform-build/zulu-src.git/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Sunday, October 9, 2022 9:42:32 AM UTC
*/

public interface UNKNOWN
{

  /**
   * XXX
   */
  public static final short value = (short)(5);
}
